"""empty message

Revision ID: 387d967b4dee
Revises: 
Create Date: 2022-10-17 11:06:25.479218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387d967b4dee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('audit_log_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('user_name', sa.String(length=75), nullable=True),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.Column('table_name', sa.String(length=130), nullable=False),
    sa.Column('primary_key', sa.String(length=255), nullable=False),
    sa.Column('dml_type', sa.String(length=20), nullable=False),
    sa.Column('old_record', sa.JSON(), nullable=True),
    sa.Column('new_record', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('audit_log_id')
    )
    op.create_table('badge',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('credential_type_id', sa.String(), nullable=True),
    sa.Column('credential_type_label', sa.String(), nullable=True),
    sa.Column('class_id', sa.String(), nullable=False),
    sa.Column('external_user_id', sa.String(), nullable=True),
    sa.Column('badge_type_uuid', sa.String(), nullable=False),
    sa.Column('badge_name', sa.String(), nullable=True),
    sa.Column('badge_description', sa.String(), nullable=True),
    sa.Column('badge_org_id', sa.String(), nullable=True),
    sa.Column('badge_org_label', sa.String(), nullable=True),
    sa.Column('badge_org_logo', sa.String(), nullable=True),
    sa.Column('badge_date', sa.String(), nullable=True),
    sa.Column('badge_external_link', sa.String(), nullable=True),
    sa.Column('badge_image', sa.String(), nullable=True),
    sa.Column('badge_json', sa.JSON(), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('learner_uuid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('badge_definition',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('badge_id', sa.BIGINT(), nullable=False),
    sa.Column('badge_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('badge_object',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('badge_def_uuid', sa.String(), nullable=False),
    sa.Column('learner_uuid', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('badge_partner',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('url')
    )
    op.create_table('badge_type',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('extrernal_partner_id', sa.String(), nullable=True),
    sa.Column('extrernal_partner_label', sa.String(), nullable=True),
    sa.Column('badge_org_type', sa.String(), nullable=True),
    sa.Column('badge_org_id', sa.String(), nullable=True),
    sa.Column('badge_org_label', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('reference_uri', sa.String(), nullable=True),
    sa.Column('image', sa.JSON(), nullable=True),
    sa.Column('attachment', sa.JSON(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('json', sa.JSON(), nullable=True),
    sa.Column('credential_type_uuid', sa.String(), nullable=True),
    sa.Column('org_uuid', sa.String(), nullable=True),
    sa.Column('entityID', sa.String(), nullable=True),
    sa.Column('auto_issue', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_badge_type_badge_org_id'), 'badge_type', ['badge_org_id'], unique=False)
    op.create_index(op.f('ix_badge_type_badge_org_label'), 'badge_type', ['badge_org_label'], unique=False)
    op.create_index(op.f('ix_badge_type_badge_org_type'), 'badge_type', ['badge_org_type'], unique=False)
    op.create_index(op.f('ix_badge_type_extrernal_partner_id'), 'badge_type', ['extrernal_partner_id'], unique=False)
    op.create_index(op.f('ix_badge_type_extrernal_partner_label'), 'badge_type', ['extrernal_partner_label'], unique=False)
    op.create_table('class',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('external_class_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=True),
    sa.Column('external_course_id', sa.String(), nullable=True),
    sa.Column('instructor_id', sa.BIGINT(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('term_id', sa.BIGINT(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('reference_uri', sa.String(), nullable=True),
    sa.Column('delivery_id', sa.BIGINT(), nullable=True),
    sa.Column('location_id', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('class_enrollment_definition',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('course_id', sa.BIGINT(), nullable=False),
    sa.Column('course_subject', sa.String(), nullable=False),
    sa.Column('course_number', sa.String(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('class_level',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('semester_order', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('college',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('credential_type_id', sa.String(), nullable=True),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('college_label', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('parent_organization', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_college_college_id'), 'college', ['college_id'], unique=False)
    op.create_table('course',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('catalog_code', sa.String(), nullable=True),
    sa.Column('reference_uri', sa.String(), nullable=True),
    sa.Column('college_id', sa.String(), nullable=True),
    sa.Column('school_id', sa.BIGINT(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('credit_hours', sa.Float(), nullable=True),
    sa.Column('course_level_id', sa.BIGINT(), nullable=True),
    sa.Column('general_ed_id_required', sa.BIGINT(), nullable=True),
    sa.Column('general_ed_id_credit', sa.String(), nullable=True),
    sa.Column('program_id_required', sa.String(), nullable=True),
    sa.Column('program_id_credit', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('credential_type_id', sa.String(), nullable=True),
    sa.Column('parent_organization', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_course_college_id'), 'course', ['college_id'], unique=False)
    op.create_index(op.f('ix_course_course_level_id'), 'course', ['course_level_id'], unique=False)
    op.create_index(op.f('ix_course_general_ed_id_credit'), 'course', ['general_ed_id_credit'], unique=False)
    op.create_index(op.f('ix_course_general_ed_id_required'), 'course', ['general_ed_id_required'], unique=False)
    op.create_index(op.f('ix_course_school_id'), 'course', ['school_id'], unique=False)
    op.create_table('course_level',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('coursework_type',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('credential_definition',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('cred_def_type', sa.String(), nullable=False),
    sa.Column('cred_def', sa.String(), nullable=False),
    sa.Column('schema', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('credential_relation',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.Column('target_cred_type_uuid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('credential_type',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('credential_definition_uuid', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('credential_type', sa.String(), nullable=True),
    sa.Column('schema_uri', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('credit_recognition_type',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('department',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('credential_type_id', sa.String(), nullable=True),
    sa.Column('department_id', sa.String(), nullable=False),
    sa.Column('department_label', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('parent_organization', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_department_credential_type_id'), 'department', ['credential_type_id'], unique=False)
    op.create_index(op.f('ix_department_department_id'), 'department', ['department_id'], unique=False)
    op.create_table('experience_category',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('parent_name', sa.String(), nullable=True),
    sa.Column('parent_id', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('experience_type',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('experience_type_id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('org_id', sa.BIGINT(), nullable=False),
    sa.Column('org_name', sa.String(), nullable=False),
    sa.Column('org_logo', sa.String(), nullable=True),
    sa.Column('experience_category_id', sa.String(), nullable=False),
    sa.Column('experience_category', sa.String(), nullable=False),
    sa.Column('experience_subcategory_id', sa.String(), nullable=True),
    sa.Column('experience_subcategory', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('general_education',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('college_id', sa.BIGINT(), nullable=True),
    sa.Column('reference_uri', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_general_education_college_id'), 'general_education', ['college_id'], unique=False)
    op.create_table('general_education_fulfillment',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('credential_type_id', sa.BIGINT(), nullable=False),
    sa.Column('credential_type_label', sa.String(), nullable=False),
    sa.Column('recognition_date', sa.DateTime(), nullable=False),
    sa.Column('term_id', sa.BIGINT(), nullable=False),
    sa.Column('term_label', sa.String(), nullable=False),
    sa.Column('gen_ed_id', sa.BIGINT(), nullable=False),
    sa.Column('credential_label', sa.String(), nullable=False),
    sa.Column('gen_ed_name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_general_education_fulfillment_credential_type_id'), 'general_education_fulfillment', ['credential_type_id'], unique=False)
    op.create_index(op.f('ix_general_education_fulfillment_gen_ed_id'), 'general_education_fulfillment', ['gen_ed_id'], unique=False)
    op.create_index(op.f('ix_general_education_fulfillment_term_id'), 'general_education_fulfillment', ['term_id'], unique=False)
    op.create_table('general_education_group_asu',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('gen_id_list', sa.BIGINT(), nullable=True),
    sa.Column('gen_code_list', sa.String(), nullable=False),
    sa.Column('credential_type_id', sa.String(), nullable=True),
    sa.Column('parent_organization', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_general_education_group_asu_gen_id_list'), 'general_education_group_asu', ['gen_id_list'], unique=False)
    op.create_table('grade',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('letter', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('instructor',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('school_id', sa.BIGINT(), nullable=True),
    sa.Column('college_id', sa.BIGINT(), nullable=False),
    sa.Column('instructor_role_id', sa.BIGINT(), nullable=False),
    sa.Column('did', sa.String(), nullable=True),
    sa.Column('reference_uri', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_instructor_college_id'), 'instructor', ['college_id'], unique=False)
    op.create_index(op.f('ix_instructor_instructor_role_id'), 'instructor', ['instructor_role_id'], unique=False)
    op.create_index(op.f('ix_instructor_school_id'), 'instructor', ['school_id'], unique=False)
    op.create_table('instructor_role',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('learners',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('email_address_type', sa.String(), nullable=True),
    sa.Column('address_type', sa.String(), nullable=True),
    sa.Column('address1', sa.String(), nullable=True),
    sa.Column('address2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('effdt_addresses', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('phone_type', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('pref_phone_flag', sa.String(), nullable=True),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_initial', sa.String(), nullable=True),
    sa.Column('effdt_names', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('otp_status', sa.Boolean(), nullable=False),
    sa.Column('user_consent', sa.Boolean(), nullable=True),
    sa.Column('consent_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('mime_type',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('mime_type1', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('organization_identity',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('credential_type_id', sa.String(), nullable=True),
    sa.Column('organization_label', sa.String(), nullable=False),
    sa.Column('organization_type_id', sa.BIGINT(), nullable=True),
    sa.Column('organization_type_label', sa.String(), nullable=True),
    sa.Column('organization_subtype_id', sa.BIGINT(), nullable=True),
    sa.Column('organization_subtype_label', sa.String(), nullable=True),
    sa.Column('organization_parent_id', sa.BIGINT(), nullable=True),
    sa.Column('organization_parent_label', sa.String(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('background', sa.String(), nullable=True),
    sa.Column('reference_url', sa.String(), nullable=True),
    sa.Column('street_1', sa.String(), nullable=False),
    sa.Column('street_2', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('parent_organization', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_organization_identity_organization_subtype_id'), 'organization_identity', ['organization_subtype_id'], unique=False)
    op.create_index(op.f('ix_organization_identity_organization_type_id'), 'organization_identity', ['organization_type_id'], unique=False)
    op.create_table('organization_level',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('organization_subtype',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('subtype_id', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('organization_type',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('subtype_id', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('organizations',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('type_id', sa.String(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=True),
    sa.Column('subtype_id', sa.String(), nullable=True),
    sa.Column('organization_subtype_name', sa.String(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('parent_name', sa.String(), nullable=True),
    sa.Column('reference_url', sa.String(), nullable=True),
    sa.Column('logo', sa.JSON(), nullable=True),
    sa.Column('background', sa.JSON(), nullable=True),
    sa.Column('mail', sa.String(), nullable=True),
    sa.Column('street_1', sa.String(), nullable=False),
    sa.Column('street_2', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('external_name', sa.String(), nullable=True),
    sa.Column('badgr_entityID', sa.String(), nullable=True),
    sa.Column('issuer_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_organizations_parent_id'), 'organizations', ['parent_id'], unique=False)
    op.create_index(op.f('ix_organizations_parent_name'), 'organizations', ['parent_name'], unique=False)
    op.create_index(op.f('ix_organizations_subtype_id'), 'organizations', ['subtype_id'], unique=False)
    op.create_index(op.f('ix_organizations_type_id'), 'organizations', ['type_id'], unique=False)
    op.create_index(op.f('ix_organizations_type_name'), 'organizations', ['type_name'], unique=False)
    op.create_table('otp',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('otp', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('portfolio_source',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('source_credential_id', sa.BIGINT(), nullable=False),
    sa.Column('source_credential_label', sa.String(), nullable=False),
    sa.Column('source_portfolio_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_portfolio_source_source_credential_id'), 'portfolio_source', ['source_credential_id'], unique=False)
    op.create_table('program',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('credential_type_id', sa.String(), nullable=True),
    sa.Column('program_id', sa.String(), nullable=False),
    sa.Column('program_label', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('program_type_label', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('parent_organization', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_program_credential_type_id'), 'program', ['credential_type_id'], unique=False)
    op.create_index(op.f('ix_program_program_id'), 'program', ['program_id'], unique=False)
    op.create_table('program_completion',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('credential_type_id', sa.BIGINT(), nullable=False),
    sa.Column('credential_type_label', sa.String(), nullable=False),
    sa.Column('recognition_date', sa.DateTime(), nullable=False),
    sa.Column('term_id', sa.BIGINT(), nullable=False),
    sa.Column('term_label', sa.String(), nullable=False),
    sa.Column('program_id', sa.BIGINT(), nullable=False),
    sa.Column('program_label', sa.String(), nullable=False),
    sa.Column('credential_label', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_program_completion_credential_type_id'), 'program_completion', ['credential_type_id'], unique=False)
    op.create_index(op.f('ix_program_completion_program_id'), 'program_completion', ['program_id'], unique=False)
    op.create_index(op.f('ix_program_completion_term_id'), 'program_completion', ['term_id'], unique=False)
    op.create_table('program_type',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('role',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('credential_type_id', sa.String(), nullable=True),
    sa.Column('parent_organization', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('school',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('credential_type_id', sa.String(), nullable=True),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('school_label', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('parent_organization', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_school_credential_type_id'), 'school', ['credential_type_id'], unique=False)
    op.create_index(op.f('ix_school_school_id'), 'school', ['school_id'], unique=False)
    op.create_table('skill_category',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('reference_uri', sa.String(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('skill_definitions',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('reference_url', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('course_code', sa.String(), nullable=True),
    sa.Column('occupation_ids', sa.String(), nullable=True),
    sa.Column('employer_ids', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('skill_type',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('Updates_for_POCKMMVP_1030', sa.String(), nullable=True),
    sa.Column('reference_url', sa.String(), nullable=True),
    sa.Column('source_skill_type_id', sa.String(), nullable=True),
    sa.Column('occupation_ids', sa.String(), nullable=True),
    sa.Column('employer_ids', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('rsd', sa.String(), nullable=True),
    sa.Column('rsd_uri', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_skill_type_employer_ids'), 'skill_type', ['employer_ids'], unique=False)
    op.create_index(op.f('ix_skill_type_occupation_ids'), 'skill_type', ['occupation_ids'], unique=False)
    op.create_table('source_skill_library',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('reference_uri', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('source_skill_type',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('source_skill_library_id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('reference_uri', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('occupations', sa.String(), nullable=True),
    sa.Column('employer', sa.String(), nullable=True),
    sa.Column('certifications', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_source_skill_type_source_skill_library_id'), 'source_skill_type', ['source_skill_library_id'], unique=False)
    op.create_table('term',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('credential_type_id', sa.String(), nullable=True),
    sa.Column('parent_organization', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('title',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('credential_type_id', sa.String(), nullable=False),
    sa.Column('credential_type_label', sa.String(), nullable=True),
    sa.Column('title_type_id', sa.BIGINT(), nullable=False),
    sa.Column('title_type_label', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('organization_label', sa.String(), nullable=False),
    sa.Column('conferral_date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('title_type',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('reference_url', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('title_type')
    op.drop_table('title')
    op.drop_table('term')
    op.drop_index(op.f('ix_source_skill_type_source_skill_library_id'), table_name='source_skill_type')
    op.drop_table('source_skill_type')
    op.drop_table('source_skill_library')
    op.drop_index(op.f('ix_skill_type_occupation_ids'), table_name='skill_type')
    op.drop_index(op.f('ix_skill_type_employer_ids'), table_name='skill_type')
    op.drop_table('skill_type')
    op.drop_table('skill_definitions')
    op.drop_table('skill_category')
    op.drop_index(op.f('ix_school_school_id'), table_name='school')
    op.drop_index(op.f('ix_school_credential_type_id'), table_name='school')
    op.drop_table('school')
    op.drop_table('role')
    op.drop_table('program_type')
    op.drop_index(op.f('ix_program_completion_term_id'), table_name='program_completion')
    op.drop_index(op.f('ix_program_completion_program_id'), table_name='program_completion')
    op.drop_index(op.f('ix_program_completion_credential_type_id'), table_name='program_completion')
    op.drop_table('program_completion')
    op.drop_index(op.f('ix_program_program_id'), table_name='program')
    op.drop_index(op.f('ix_program_credential_type_id'), table_name='program')
    op.drop_table('program')
    op.drop_index(op.f('ix_portfolio_source_source_credential_id'), table_name='portfolio_source')
    op.drop_table('portfolio_source')
    op.drop_table('otp')
    op.drop_index(op.f('ix_organizations_type_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_type_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_subtype_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_parent_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_parent_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('organization_type')
    op.drop_table('organization_subtype')
    op.drop_table('organization_level')
    op.drop_index(op.f('ix_organization_identity_organization_type_id'), table_name='organization_identity')
    op.drop_index(op.f('ix_organization_identity_organization_subtype_id'), table_name='organization_identity')
    op.drop_table('organization_identity')
    op.drop_table('mime_type')
    op.drop_table('learners')
    op.drop_table('instructor_role')
    op.drop_index(op.f('ix_instructor_school_id'), table_name='instructor')
    op.drop_index(op.f('ix_instructor_instructor_role_id'), table_name='instructor')
    op.drop_index(op.f('ix_instructor_college_id'), table_name='instructor')
    op.drop_table('instructor')
    op.drop_table('grade')
    op.drop_index(op.f('ix_general_education_group_asu_gen_id_list'), table_name='general_education_group_asu')
    op.drop_table('general_education_group_asu')
    op.drop_index(op.f('ix_general_education_fulfillment_term_id'), table_name='general_education_fulfillment')
    op.drop_index(op.f('ix_general_education_fulfillment_gen_ed_id'), table_name='general_education_fulfillment')
    op.drop_index(op.f('ix_general_education_fulfillment_credential_type_id'), table_name='general_education_fulfillment')
    op.drop_table('general_education_fulfillment')
    op.drop_index(op.f('ix_general_education_college_id'), table_name='general_education')
    op.drop_table('general_education')
    op.drop_table('experience_type')
    op.drop_table('experience_category')
    op.drop_index(op.f('ix_department_department_id'), table_name='department')
    op.drop_index(op.f('ix_department_credential_type_id'), table_name='department')
    op.drop_table('department')
    op.drop_table('credit_recognition_type')
    op.drop_table('credential_type')
    op.drop_table('credential_relation')
    op.drop_table('credential_definition')
    op.drop_table('coursework_type')
    op.drop_table('course_level')
    op.drop_index(op.f('ix_course_school_id'), table_name='course')
    op.drop_index(op.f('ix_course_general_ed_id_required'), table_name='course')
    op.drop_index(op.f('ix_course_general_ed_id_credit'), table_name='course')
    op.drop_index(op.f('ix_course_course_level_id'), table_name='course')
    op.drop_index(op.f('ix_course_college_id'), table_name='course')
    op.drop_table('course')
    op.drop_index(op.f('ix_college_college_id'), table_name='college')
    op.drop_table('college')
    op.drop_table('class_level')
    op.drop_table('class_enrollment_definition')
    op.drop_table('class')
    op.drop_index(op.f('ix_badge_type_extrernal_partner_label'), table_name='badge_type')
    op.drop_index(op.f('ix_badge_type_extrernal_partner_id'), table_name='badge_type')
    op.drop_index(op.f('ix_badge_type_badge_org_type'), table_name='badge_type')
    op.drop_index(op.f('ix_badge_type_badge_org_label'), table_name='badge_type')
    op.drop_index(op.f('ix_badge_type_badge_org_id'), table_name='badge_type')
    op.drop_table('badge_type')
    op.drop_table('badge_partner')
    op.drop_table('badge_object')
    op.drop_table('badge_definition')
    op.drop_table('badge')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
